INSERT INTO RATING (RATING_NAME)
SELECT 'G'
WHERE NOT EXISTS (
    SELECT 1 FROM RATING WHERE RATING_NAME = 'G'
);
INSERT INTO RATING (RATING_NAME)
SELECT 'PG'
WHERE NOT EXISTS (
    SELECT 1 FROM RATING WHERE RATING_NAME = 'PG'
);
INSERT INTO RATING (RATING_NAME)
SELECT 'PG-13'
WHERE NOT EXISTS (
    SELECT 1 FROM RATING WHERE RATING_NAME = 'PG-13'
);
INSERT INTO RATING (RATING_NAME)
SELECT 'R'
WHERE NOT EXISTS (
    SELECT 1 FROM RATING WHERE RATING_NAME = 'R'
);
INSERT INTO RATING (RATING_NAME)
SELECT 'NC-17'
WHERE NOT EXISTS (
    SELECT 1 FROM RATING WHERE RATING_NAME = 'NC-17'
);

INSERT INTO GENRE (GENRE_NAME)
SELECT 'Комедия'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRE WHERE GENRE_NAME = 'Комедия'
);
INSERT INTO GENRE (GENRE_NAME)
SELECT 'Драма'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRE WHERE GENRE_NAME = 'Драма'
);
INSERT INTO GENRE (GENRE_NAME)
SELECT 'Мультфильм'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRE WHERE GENRE_NAME = 'Мультфильм'
);
INSERT INTO GENRE (GENRE_NAME)
SELECT 'Триллер'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRE WHERE GENRE_NAME = 'Триллер'
);
INSERT INTO GENRE (GENRE_NAME)
SELECT 'Документальный'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRE WHERE GENRE_NAME = 'Документальный'
);
INSERT INTO GENRE (GENRE_NAME)
SELECT 'Боевик'
WHERE NOT EXISTS (
    SELECT 1 FROM GENRE WHERE GENRE_NAME = 'Боевик'
);