create table IF NOT EXISTS RATING
(
    RATING_ID   INTEGER auto_increment,
    RATING_NAME VARCHAR(10),
    constraint RATING_PK
        primary key (RATING_ID)
);

create table IF NOT EXISTS GENRE
(
    GENRE_ID   INTEGER auto_increment,
    GENRE_NAME VARCHAR(20),
    constraint "GENRE_pk"
        primary key (GENRE_ID)
);

create table IF NOT EXISTS FILM
(
    FILM_ID      INTEGER generated by default as identity primary key,
    FILM_NAME    VARCHAR(100) not null,
    DESCRIPTION  VARCHAR(200),
    RELEASE_DATE DATE,
    DURATION     INTEGER,
    RATING_ID    INTEGER,
    constraint "FILM_RATING_null_fk"
        foreign key (RATING_ID) references RATING
);

create table IF NOT EXISTS FILM_GENRE
(
    FILM_ID  INTEGER,
    GENRE_ID INTEGER,
    constraint "FILM_GENRE_FILM_null_fk"
        foreign key (FILM_ID) references FILM,
    constraint "FILM_GENRE_GENRE_null_fk"
        foreign key (GENRE_ID) references GENRE
);

create table IF NOT EXISTS USERS
(
    USER_ID  INTEGER generated by default as identity primary key,
    EMAIL    VARCHAR(30) not null,
    LOGIN    VARCHAR(50),
    NAME     VARCHAR(100),
    BIRTHDAY DATE
);

create table IF NOT EXISTS FILM_USERS_LIKES
(
    FILM_ID INTEGER,
    USER_ID INTEGER,
    constraint "FILM_USERS_LIKES_FILM_null_fk"
        foreign key (FILM_ID) references FILM,
    constraint "FILM_USERS_LIKES_USERS_null_fk"
        foreign key (USER_ID) references USERS
);

create table IF NOT EXISTS FRIENDS
(
    FRIEND_1     INTEGER,
    FRIEND_2     INTEGER,
    CONFIRMATION BOOLEAN not null,
    constraint "FRIENDS_USERS_null_fk1"
        foreign key (FRIEND_1) references USERS,
    constraint "FRIENDS_USERS_null_fk2"
        foreign key (FRIEND_2) references USERS
);
